worker_processes 1;
daemon off;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    types {
        video/mp4 mp4;
    }

    server {
        listen 7860;
        server_name _;

        location / {
            root /app/frontend;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /demo/ {
            root /app/frontend;
            try_files $uri =404;
            add_header Access-Control-Allow-Origin *;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /visionapi/ {
            proxy_pass http://127.0.0.1:8010/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            proxy_buffering off;
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
            chunked_transfer_encoding off;
        }
    }
}
